### ISSUE TITLE
Add declarationMap:true to tsconfig for correct ctrl-click go-to-source

### ISSUE THREAD

**Issue by wingedrhino** [tinyhttp/tinyhttp#357]
Currently, ctrl+click on a `tinyhttp` export from VS Code goes to the `.d.ts` file instead of going to the function source code. Adding `"declarationMap": true` to `tsconfig.json` would generate `.js.map` files. For example, take a look here https://github.com/wingedrhino/node-pipespawn/tree/master/dist

I'd love to add this to `tinyhttp`, but every other package that's been moved to its own dedicated repository would also need to be updated for this to be actually useful.

If you're happy to accept merge requests, I can start submitting them one at a time!

**Comment by talentlessguy** [comment]
yeah I'm fine you can make em

**Comment by aarontravass** [comment]
I'll take this up.

**Comment by aarontravass** [comment]
Was looking at ts docs and I reckon we should turn on `sourceMap` and `composite`. `sourceMap` helps map the ts files and `composite` decreases type checking time since it references previous built files.

Related links
https://www.typescriptlang.org/tsconfig#sourceMap
https://www.typescriptlang.org/tsconfig#composite

**Comment by talentlessguy** [comment]
thanks to @aarontravass it's now present in monorepo
