### ISSUE TITLE
Wildcards strip the first character from `req.url`

### ISSUE THREAD

**Issue by adhusson** [tinyhttp/tinyhttp#417]
**Describe the bug**

Wildcards (`*`) don't correctly populate the URL on `/`-prefixed paths: they strip the first character.

**To Reproduce**

```js
import { App } from '@tinyhttp/app'

const app = new App()

app.get('/foo/*',(req,res) => {
  console.log(req.url);
  // on GET /foo/bar
  // should show @/bar
  //   will show @/ar
  res.send(`@${req.url}`);
});

app.listen(3001);
```

**Expected behavior**

Should show `@/bar`

**Versions**

- `node`: 16
- `@tinyhttp/app`: 2.2.0

**Comment by aarontravass** [comment]
Thanks for reporting this issue. The bug lies due to the way the `req.url` is property is set when a `*` is present

https://github.com/tinyhttp/tinyhttp/blob/ed51d60c760a34e0b944603e6b81f6295b129fd3/packages/app/src/app.ts#L368

A PR is welcome

**Comment by adhusson** [comment]
I'll look at making a PR but I'm not sure about 2 things:
- When the path is `/foo/:pat` and the url is `/foo/bar` is it expected that the url becomes `/foo` (I would have expected the URL to remain unchanged)
- When the path is `/foo/*` and the url is `/foo/bar` should the url become `/foo` or `/foo/bar`?

**Comment by aarontravass** [comment]
> When the path is /foo/:pat and the url is /foo/bar is it expected that req.url becomes / (I would have expected the URL to remain unchanged)?

As per express, `req.url` is `/foo/bar` when the path is `/foo/:param`

> When the path is /foo/* and the url is /foo/bar should req.url become /foo or /foo/bar or /bar?

Since the aim is to offer similar APIs to express, `req.url` should output `/foo/bar`.

**Comment by aarontravass** [comment]
Here's the express code

```js
import express from 'express'

const app = express()

app.get('/foo/:path',(req,res) => {
  console.log(req.url, req.params);
  res.send(`@${req.url}`);
});

app.get('/hello/*',(req,res) => {
  console.log(req.url, req.params);
  res.send(`@${req.url}`);
});

app.listen(3000);
```

**Comment by talentlessguy** [comment]
Thanks for reporting - seems like a very simple bugfix - PR is welcome as said above

**Comment by adhusson** [comment]
@aarontravass What you descibe as express's spec is not what I observe with tinyhttp:

```javascript
// shows @/ on /x/bar
app.get('/x/:y',(req,res) => {
  res.send(`@${req.url}`);
});
```

This is probably a different issue from the one I mentioned above, which I'm reproducing here:

```javascript
// shows @/ar on /foo/bar
app.get('/foo/*',(req,res) => {
  res.send(`@${req.url}`);
});
```

Finally I'm seeing a similar but maybe unrelated behavior:

```javascript
// shows @/bar @/ar @/ on /z/bar
app.use('/z',router,router,router,(req,res) => {
  res.send(`@${urls.join(' @')}`);
  urls = [];
});
```

I'm guessing all of the above needs to be fixed but I'm waiting to get your input on that.

**Comment by aarontravass** [comment]
Looks like the code for `req.url` when a param is present is broken as well. The buggy line is

https://github.com/tinyhttp/tinyhttp/blob/ed51d60c760a34e0b944603e6b81f6295b129fd3/packages/app/src/app.ts#L365

> Finally I'm seeing a similar but maybe unrelated behavior:

This issue is cause by modifying the original request object. Essentially, [Line 368](https://github.com/tinyhttp/tinyhttp/blob/ed51d60c760a34e0b944603e6b81f6295b129fd3/packages/app/src/app.ts#L368), as mentioned by your original post, keeps stripping the first character and it does so for all middle wares. Good catch!

**Comment by aarontravass** [comment]
>  I don't understand how handle, as it is today, differentiates between a route (app.get, etc) and a middleware (app.use).

There is not much different between a route and a middleware. In fact, if you look at packages/router/src/index.ts, you'll find that routes are pretty much similar to middlware

https://github.com/tinyhttp/tinyhttp/blob/585633f025434bea3a12d9dbfdf07fb59712c8a8/packages/router/src/index.ts#L202

The only difference is that routes are 'mounted' on the app itself and hence, do not need an extra path variable (also called `fullPath` in the code) while middlwares do. This is due to the fact that you can mount middlewares such as subapps onto a specific path.

 > Replacing the current logic with the logic I describe above is quite a big change so I'd like to check with you that it makes sense:

Yes, your idea is correct.

**Comment by aarontravass** [comment]
> Replacing the current logic with the logic I describe above is quite a big change so I'd like to check with you that it makes sense:

I believe the fix should be pretty simple since all you need to do is differentiate correctly between a route and a middlware.
